-- AlterTable
ALTER TABLE "players" ADD COLUMN "current_hp" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "last_hp_regen_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "is_recovering" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "recovery_cost" INTEGER;
